site_name: Mechanika Mechanismů

theme: readthedocs

plugins:
  - search
  - awesome-pages

markdown_extensions:
  - footnotes
  - markdown_katex:
      no_inline_svg: True
      insert_fonts_css: True